# Generated by Django 4.0.6 on 2023-01-26 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_offerride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerride',
            name='user',
        ),
        migrations.AddField(
            model_name='offerride',
            name='emai_id',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerride',
            name='uname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
