# Generated by Django 4.0.6 on 2023-01-26 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0004_remove_offerride_user_offerride_emai_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerride',
            name='datetime',
        ),
        migrations.AddField(
            model_name='offerride',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
