# Generated by Django 4.0.6 on 2023-02-05 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0007_offeraride_noofpassenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offeraride',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='offeraride',
            old_name='emai_id',
            new_name='email_id',
        ),
    ]
