# Generated by Django 4.0.6 on 2023-02-13 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0009_user_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeraride',
            name='phoneNo',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
