# Generated by Django 4.0.6 on 2023-03-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0010_offeraride_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeraride',
            name='phoneNo',
            field=models.CharField(max_length=12),
        ),
    ]
