# Generated by Django 4.0.6 on 2023-04-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0011_alter_offeraride_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noOfRaters',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(max_length=5, null=True),
        ),
    ]
