# Generated by Django 4.0.6 on 2023-04-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0012_user_noofraters_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='noOfRaters',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
